from prometheus_client import Counter, Gauge, Histogram
import config

SIGNALS_GENERATED = Counter(
    "strategy_signals_generated_total",
    "Total number of trade signals generated by the strategy",
    ["ticker", "action"]
)

BARS_PROCESSED = Counter(
    "strategy_bars_processed_total",
    "Total number of market data bars processed by the strategy",
    ["ticker"]
)

STRATEGY_LATENCY = Histogram(
    "strategy_execution_duration_seconds",
    "Time taken in seconds to run on_bar calculation and indicator updates",
    ["ticker"]
)

INDICATOR_VALUE = Gauge(
    "strategy_indicator_value",
    "Latest value of key mathematical indicators in the strategy",
    ["ticker", "indicator_name"]
)

# Pre-initialize metric sample lines so Prometheus exports them immediately with value 0.0 at boot
if hasattr(config, "TICKER") and config.TICKER:
    BARS_PROCESSED.labels(ticker=config.TICKER).inc(0)
    SIGNALS_GENERATED.labels(ticker=config.TICKER, action="BUY").inc(0)
    SIGNALS_GENERATED.labels(ticker=config.TICKER, action="SELL").inc(0)
