apiVersion: v1
kind: Service
metadata:
  name: {{ include "tick-lb.fullname" . }}
  labels:
    {{- include "tick-lb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc-proxy
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc-proxy
    - name: http-admin
      port: {{ .Values.service.adminPort }}
      targetPort: http-admin
  selector:
    {{- include "tick-lb.selectorLabels" . | nindent 4 }}
