apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connection-manager-alpaca.fullname" . }}-secret
  labels:
    {{- include "connection-manager-alpaca.labels" . | nindent 4 }}
type: Opaque
stringData:
  ALPACA_API_KEY: {{ .Values.secret.alpacaApiKey | quote }}
  ALPACA_SECRET_KEY: {{ .Values.secret.alpacaSecretKey | quote }}
