apiVersion: v1
kind: Service
metadata:
  name: {{ include "connection-manager-alpaca.fullname" . }}
  labels:
    {{- include "connection-manager-alpaca.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-health
      port: {{ .Values.service.httpPort }}
      targetPort: http-health
    - name: grpc-trading
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc-trading
  selector:
    {{- include "connection-manager-alpaca.selectorLabels" . | nindent 4 }}
