# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import connection_manager_pb2 as connection__manager__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in connection_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
    )


class MarketDataServiceStub:
    """Market Data Subscription Interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMarketData = channel.unary_stream(
                '/trading.connection.MarketDataService/StreamMarketData',
                request_serializer=connection__manager__pb2.MarketDataRequest.SerializeToString,
                response_deserializer=connection__manager__pb2.MarketDataResponse.FromString,
                _registered_method=True)
        self.GetHistoricalBars = channel.unary_unary(
                '/trading.connection.MarketDataService/GetHistoricalBars',
                request_serializer=connection__manager__pb2.HistoricalBarsRequest.SerializeToString,
                response_deserializer=connection__manager__pb2.HistoricalBarsResponse.FromString,
                _registered_method=True)


class MarketDataServiceServicer:
    """Market Data Subscription Interface
    """

    def StreamMarketData(self, request, context):
        """Streams real-time market data ticks (Server Streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalBars(self, request, context):
        """Queries historical bars for strategy warm-up (Unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
